/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['input.ng-invalid[_ngcontent-%COMP%] {\n    border-left-color: deeppink;\n    border-left-style: solid;\n    border-left-width: 5px;\n}\n\ninput.ng-valid[_ngcontent-%COMP%] {\n    border-left-color: chartreuse;\n    border-left-style: solid;\n    border-left-width: 5px;\n}'];